**DATA_ANALYSIS**
--DETERMINE_WHETHER_PAID_APPS_HAVE_HIGHER_RATINGS_THAN_FREE_APPS
SELECT CASE
WHEN price > 0 THEN 'PAID'
ELSE 'FREE'
END AS App_Type,
avg(user_rating) AS Avg_rating
FROM AppleStore
GROUP BY App_type

